package CASA;



import com.mathworks.toolbox.javabuilder.MWNumericArray;
import com.mathworks.toolbox.javabuilder.MWArray;
import com.mathworks.toolbox.javabuilder.MWCharArray;
import com.mathworks.toolbox.javabuilder.MWException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import cellsignalinganalysis.Utils;
import com.matlab.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mahsa.moein
 */
public class SignalAnalysis extends javax.swing.JFrame {

    /**
     * Creates new form SignalAnalysis
     */
    
   
    private javax.swing.JFileChooser fc;
    public SignalAnalysis() 
    {
        initComponents();
        setLocationRelativeTo(null);
        jTxtDestFolder.setEditable(false);
        jTxtFolderName.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFolderName = new javax.swing.JTextField();
        jTxtDestFolder = new javax.swing.JTextField();
        jBtnFolderBrowse = new javax.swing.JButton();
        jBtnDestBrowse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtTimeColumn = new javax.swing.JTextField();
        jBtnOpenSig = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtcolNumber = new javax.swing.JTextField();
        jCbxNormalize = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Signal Folder:");

        jLabel2.setText("Denoised Signal Folder:");

        jBtnFolderBrowse.setText("Browse...");
        jBtnFolderBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFolderBrowseActionPerformed(evt);
            }
        });

        jBtnDestBrowse.setText("Browse...");
        jBtnDestBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDestBrowseActionPerformed(evt);
            }
        });

        jLabel3.setText("Time Column Number:");

        jBtnOpenSig.setText("Open Signals");
        jBtnOpenSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpenSigActionPerformed(evt);
            }
        });

        jLabel4.setText("Intensity Column Number:");

        jCbxNormalize.setText("Normalize Signal");
        jCbxNormalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxNormalizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtTimeColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtcolNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbxNormalize))
                    .addComponent(jTxtDestFolder)
                    .addComponent(jTxtFolderName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnFolderBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jBtnDestBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnOpenSig, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnFolderBrowse))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBtnDestBrowse)
                    .addComponent(jTxtDestFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtTimeColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtcolNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbxNormalize)
                    .addComponent(jBtnOpenSig))
                .addContainerGap(446, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDestBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDestBrowseActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            
            if(jTxtFolderName.getText().equals(fc.getSelectedFile().getAbsolutePath()))
            {
              JOptionPane.showMessageDialog(this, "Destination folder cannot be the same with source folder "); 
              return;
            }
            else
            {
                jTxtDestFolder.setText(fc.getSelectedFile().getAbsolutePath());
            }
                               
        }
        
    }//GEN-LAST:event_jBtnDestBrowseActionPerformed

    private void jBtnFolderBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFolderBrowseActionPerformed
        // TODO add your handling code here:
         //try{        
        fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
           
            if(!Utils.CheckFolder(file.getAbsolutePath()))
            {
                JOptionPane.showMessageDialog(this, "The selected folder does not contain files with '.xls' or '.dat' extension ");           
                return;
            }
            else
            {
                jTxtFolderName.setText(fc.getSelectedFile().getAbsolutePath());               
            }
            
            jTxtFolderName.setText(fc.getSelectedFile().getAbsolutePath());     
        }
    }//GEN-LAST:event_jBtnFolderBrowseActionPerformed

    private void jBtnOpenSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpenSigActionPerformed
        // TODO add your handling code here:
        
        boolean fieldOK = true;
        int NormalizeSignal = 0;
        try 
        {
            Float.parseFloat(String.valueOf(jTxtTimeColumn.getText()));
        }

        catch ( NumberFormatException exc)
        {
            //JOptionPane.showMessageDialog(this, "Please enter an number in the Time Between Two Intensity field");
            fieldOK = false;
            jTxtTimeColumn.setText("");
        }
         
        
         if("".equals(jTxtFolderName.getText()))
         { 
             fieldOK = false;
         }
         
         if("".equals(jTxtDestFolder.getText()))
         {   
             fieldOK = false;        
         }
         
         if(!fieldOK)
         {
             JOptionPane.showMessageDialog(this, "Please fill the fields correctly"); 
             return;
         }
         
        
         
         if(jCbxNormalize.isSelected())
         {
             NormalizeSignal = 1;
         }
         
         
         
         
         
//         Object[] result = null;
//        
//         MWCharArray signalFolderPath = null;
//         MWCharArray destFolderPath = null;
//         MWNumericArray time_Column = null;
//         MWNumericArray intensityColumn = null;
//         MWNumericArray normalize_Signal = null;
//         MWNumericArray out = null;
//         com.matlab.Denoise cd = null;
//         try
//         {
//            cd = new com.matlab.Denoise();
//            signalFolderPath = new MWCharArray(jTxtFolderName.getText());
//            destFolderPath = new MWCharArray(jTxtDestFolder.getText());
//            time_Column = new MWNumericArray(Integer.parseInt(jTxtTimeColumn.getText()));
//            intensityColumn = new MWNumericArray(Integer.parseInt(jTxtcolNumber.getText()));
//            normalize_Signal = new MWNumericArray(NormalizeSignal);        
//            result = cd.denoise_Signal(1,signalFolderPath,destFolderPath,time_Column,intensityColumn,normalize_Signal);
// 
//            out =(MWNumericArray)result[0];
//            
//            if(Integer.parseInt(out.toString())== 1)
//            {
//                System.out.println(out);
//                jTxtFolderName.setText("");
//                jTxtDestFolder.setText("");
//                jTxtTimeColumn.setText("");
//                jTxtcolNumber.setText("");
//                jCbxNormalize.setSelected(false);
//                
//                jBtnOpenSig.disable();
//                //draw signals
//            }
//            
//            //System.out.println(out);
//         }
//         catch(MWException e)
//         {
//            e.printStackTrace();
//            System.out.println(e.toString());
//         }
//         finally
//         {
//            
//            MWArray.disposeArray(out);           
//            MWArray.disposeArray(result);
//            MWArray.disposeArray(signalFolderPath);
//            MWArray.disposeArray(destFolderPath);
//            MWArray.disposeArray(time_Column);
//            MWArray.disposeArray(intensityColumn);
//            MWArray.disposeArray(normalize_Signal);
//         }
         
    }//GEN-LAST:event_jBtnOpenSigActionPerformed

    private void jCbxNormalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxNormalizeActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCbxNormalizeActionPerformed

    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignalAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignalAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignalAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignalAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SignalAnalysis().setVisible(true);
//            }
//        });
//    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDestBrowse;
    private javax.swing.JButton jBtnFolderBrowse;
    private javax.swing.JButton jBtnOpenSig;
    private javax.swing.JCheckBox jCbxNormalize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTxtDestFolder;
    private javax.swing.JTextField jTxtFolderName;
    private javax.swing.JTextField jTxtTimeColumn;
    private javax.swing.JTextField jTxtcolNumber;
    // End of variables declaration//GEN-END:variables
}
